require('dotenv').config()
const mongoose = require('mongoose')
const Movie    = require('./models/Movie')

const movies = [
  // ═══════════════════════════════════════════════════════════════
  //  ФИЛЬМЫ (id: 1–35)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 1, title: 'Дюна: Часть вторая', originalTitle: 'Dune: Part Two', year: 2024,
    genres: ['Фантастика', 'Боевик'], rating: 8.5,
    description: 'Пол Атрейдес объединяется с Чани и фрименами, стремясь отомстить заговорщикам, уничтожившим его семью.',
    shortDesc: 'Пол ведёт фременов к войне против императора.',
    poster: 'https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    duration: 166, age: 16, country: 'США', director: 'Дени Вильнёв',
    cast: ['Тимоти Шаламе', 'Зендея', 'Ребекка Фергюсон'],
    trailerUrl: 'https://www.youtube.com/embed/Way9Dexny3w', type: 'movie', isFeatured: true,
  },
  {
    id: 2, title: 'Оппенгеймер', originalTitle: 'Oppenheimer', year: 2023,
    genres: ['Драма', 'Триллер'], rating: 8.9,
    description: 'История Дж. Роберта Оппенгеймера и его роли в разработке атомной бомбы в рамках Манхэттенского проекта.',
    shortDesc: 'Отец атомной бомбы и его внутренний конфликт.',
    poster: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg',
    duration: 180, age: 16, country: 'США', director: 'Кристофер Нолан',
    cast: ['Киллиан Мёрфи', 'Эмили Блант', 'Мэтт Дэймон'],
    trailerUrl: 'https://www.youtube.com/embed/uYPbbksJxIg', type: 'movie', isFeatured: true,
  },
  {
    id: 3, title: 'Интерстеллар', originalTitle: 'Interstellar', year: 2014,
    genres: ['Фантастика', 'Драма'], rating: 9.0,
    description: 'Когда засуха приводит человечество к кризису, исследователи проходят через червоточину в поисках нового дома.',
    shortDesc: 'Путешествие через червоточину ради спасения человечества.',
    poster: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    duration: 169, age: 12, country: 'США', director: 'Кристофер Нолан',
    cast: ['Мэттью МакКонахи', 'Энн Хэтэуэй', 'Джессика Честейн'],
    trailerUrl: 'https://www.youtube.com/embed/zSWdZVtXT7E', type: 'movie', isFeatured: true,
  },
  {
    id: 4, title: 'Начало', originalTitle: 'Inception', year: 2010,
    genres: ['Боевик', 'Триллер', 'Фантастика'], rating: 8.8,
    description: 'Вор, крадущий корпоративные секреты из снов людей, получает задание внедрить идею в подсознание.',
    shortDesc: 'Кража идей из снов на самом опасном уровне.',
    poster: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/s2bT29y0ngXxxu2IA8AOzzXTRhd.jpg',
    duration: 148, age: 12, country: 'США', director: 'Кристофер Нолан',
    cast: ['Леонардо ДиКаприо', 'Джозеф Гордон-Левитт', 'Элиот Пейдж'],
    trailerUrl: 'https://www.youtube.com/embed/YoHD9XEInc0', type: 'movie',
  },
  {
    id: 5, title: 'Джокер', originalTitle: 'Joker', year: 2019,
    genres: ['Драма', 'Триллер'], rating: 8.4,
    description: 'История происхождения самого известного злодея DC — неудачливого комика Артура Флека.',
    shortDesc: 'Как рождается главный злодей Готэма.',
    poster: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1ZqieMLkXQO.jpg',
    duration: 122, age: 18, country: 'США', director: 'Тодд Филлипс',
    cast: ['Хоакин Феникс', 'Роберт Де Ниро', 'Зази Битц'],
    trailerUrl: 'https://www.youtube.com/embed/zAGVQLHvwOY', type: 'movie',
  },
  {
    id: 6, title: 'Аватар 2', originalTitle: 'Avatar: The Way of Water', year: 2022,
    genres: ['Фантастика', 'Боевик'], rating: 7.6,
    description: 'Джейк Салли и Нейтири основали семью. Когда угроза возвращается, они вынуждены покинуть дом.',
    shortDesc: 'Семья Салли бежит под воду, спасаясь от врагов.',
    poster: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/s16H6tpK2utvwpaPascal7BsANkW.jpg',
    duration: 192, age: 12, country: 'США', director: 'Джеймс Кэмерон',
    cast: ['Сэм Уортингтон', 'Зои Салдана', 'Сигурни Уивер'],
    trailerUrl: 'https://www.youtube.com/embed/d9MyW72ELq0', type: 'movie',
  },
  {
    id: 7, title: 'Матрица', originalTitle: 'The Matrix', year: 1999,
    genres: ['Боевик', 'Фантастика'], rating: 8.7,
    description: 'Программист Нео начинает подозревать, что мир — симуляция, и встречает людей, знающих правду.',
    shortDesc: 'Что если реальность — это симуляция? Один человек узнает правду.',
    poster: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
    duration: 136, age: 16, country: 'США', director: 'Сёстры Вачовски',
    cast: ['Киану Ривз', 'Лоуренс Фишбёрн', 'Кэрри-Энн Мосс'],
    trailerUrl: 'https://www.youtube.com/embed/vKQi3bBA1y8', type: 'movie',
  },
  {
    id: 8, title: 'Властелин колец: Братство кольца', originalTitle: 'The Lord of the Rings: The Fellowship of the Ring', year: 2001,
    genres: ['Фэнтези', 'Боевик'], rating: 8.8,
    description: 'Хоббит Фродо отправляется в опасное путешествие, чтобы уничтожить Кольцо всевластия.',
    shortDesc: 'Девять путников против тьмы, которая накрывает Средиземье.',
    poster: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/pIgZek5Jj0MvKbODQgzQ6DroHOX.jpg',
    duration: 178, age: 12, country: 'Новая Зеландия', director: 'Питер Джексон',
    cast: ['Элайджа Вуд', 'Иэн МакКеллен', 'Вигго Мортенсен'],
    trailerUrl: 'https://www.youtube.com/embed/V75dMMIW2B4', type: 'movie',
  },
  {
    id: 9, title: 'Тёмный рыцарь', originalTitle: 'The Dark Knight', year: 2008,
    genres: ['Боевик', 'Криминал', 'Драма'], rating: 9.0,
    description: 'Бэтмен сталкивается с Джокером — анархистом, жаждущим посеять хаос в Готэм-сити.',
    shortDesc: 'Джокер против Бэтмена. Лучший супергеройский фильм всех времён.',
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    duration: 152, age: 16, country: 'США', director: 'Кристофер Нолан',
    cast: ['Кристиан Бэйл', 'Хит Леджер', 'Аарон Экхарт'],
    trailerUrl: 'https://www.youtube.com/embed/EXeTwQWrcwY', type: 'movie', isFeatured: true,
  },
  {
    id: 10, title: 'Побег из Шоушенка', originalTitle: 'The Shawshank Redemption', year: 1994,
    genres: ['Драма'], rating: 9.3,
    description: 'Банкир Энди Дюфрейн осуждён за убийство жены и её любовника. Попав в тюрьму Шоушенк, он сохраняет надежду.',
    shortDesc: 'Самый обнадёживающий фильм о заключении и свободе.',
    poster: 'https://image.tmdb.org/t/p/w500/lyQBXzOQSuE59IsHyhrp0qIiPAz.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    duration: 142, age: 16, country: 'США', director: 'Фрэнк Дарабонт',
    cast: ['Тим Роббинс', 'Морган Фримен'],
    trailerUrl: 'https://www.youtube.com/embed/6hB3S9bIaco', type: 'movie',
  },
  {
    id: 11, title: 'Бойцовский клуб', originalTitle: 'Fight Club', year: 1999,
    genres: ['Драма', 'Триллер'], rating: 8.8,
    description: 'Неудовлетворённый менеджер знакомится с харизматичным Тайлером и основывает подпольный бойцовский клуб.',
    shortDesc: 'Первое правило: не говори о бойцовском клубе.',
    poster: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzVlhWk.jpg',
    duration: 139, age: 18, country: 'США', director: 'Дэвид Финчер',
    cast: ['Брэд Питт', 'Эдвард Нортон', 'Хелена Бонэм Картер'],
    trailerUrl: 'https://www.youtube.com/embed/SUXWAEX2jlg', type: 'movie',
  },
  {
    id: 12, title: 'Паразит', originalTitle: 'Parasite', year: 2019,
    genres: ['Триллер', 'Драма', 'Комедия'], rating: 8.5,
    description: 'Бедная корейская семья постепенно просачивается в богатый дом. Когда секрет раскрывается, всё рушится.',
    shortDesc: 'Оскар за лучший фильм. Острая социальная сатира.',
    poster: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG8.jpg',
    duration: 132, age: 16, country: 'Южная Корея', director: 'Пон Джун-хо',
    cast: ['Сон Кан-хо', 'Ли Сон-гюн', 'Чо Ё-джон'],
    trailerUrl: 'https://www.youtube.com/embed/5xH0HfJHsaY', type: 'movie',
  },
  {
    id: 13, title: 'Форрест Гамп', originalTitle: 'Forrest Gump', year: 1994,
    genres: ['Драма', 'Комедия'], rating: 8.8,
    description: 'Простодушный Форрест Гамп неожиданно для себя становится участником ключевых событий американской истории.',
    shortDesc: 'Жизнь как коробка шоколадных конфет.',
    poster: 'https://image.tmdb.org/t/p/w500/h5J4W4veyxMXDMjeMLxOs9xqNPF.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/qdIMHd4sEoBAi16gHZGRhLmCOFn.jpg',
    duration: 142, age: 12, country: 'США', director: 'Роберт Земекис',
    cast: ['Том Хэнкс', 'Робин Райт', 'Гэри Синиз'],
    trailerUrl: 'https://www.youtube.com/embed/bLvqoHBptjg', type: 'movie',
  },
  {
    id: 14, title: 'Гладиатор', originalTitle: 'Gladiator', year: 2000,
    genres: ['Боевик', 'Драма', 'Исторический'], rating: 8.5,
    description: 'Генерал Максим превращается в раба и гладиатора, жаждя мести против коварного императора Коммода.',
    shortDesc: 'Моё имя — Максим Децим Меридий. Отец убитого солдата.',
    poster: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/6WBIzCgmDCYrqh64yDREGeDk9d3.jpg',
    duration: 155, age: 16, country: 'США', director: 'Ридли Скотт',
    cast: ['Рассел Кроу', 'Хоакин Феникс', 'Кончита Феррер'],
    trailerUrl: 'https://www.youtube.com/embed/owK1qxDselE', type: 'movie',
  },
  {
    id: 15, title: 'Топ Ган: Мэверик', originalTitle: 'Top Gun: Maverick', year: 2022,
    genres: ['Боевик', 'Драма'], rating: 8.3,
    description: 'Легендарный лётчик Мэверик тренирует новое поколение пилотов для выполнения опасной миссии.',
    shortDesc: 'Спустя 36 лет: самый зрелищный боевик о пилотах.',
    poster: 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg',
    duration: 131, age: 12, country: 'США', director: 'Джозеф Косински',
    cast: ['Том Круз', 'Майлз Теллер', 'Дженнифер Коннелли'],
    trailerUrl: 'https://www.youtube.com/embed/qSqVVswa420', type: 'movie',
  },
  {
    id: 16, title: 'Всё везде и сразу', originalTitle: 'Everything Everywhere All at Once', year: 2022,
    genres: ['Фантастика', 'Боевик', 'Комедия'], rating: 8.0,
    description: 'Китайская прачечница получает способность путешествовать по мультивселенным и должна спасти мир.',
    shortDesc: 'Безумная мультивселенная, налоговая и мама в главных ролях.',
    poster: 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/hTExot1sfn7dHZjGiDSp9zOwMm8.jpg',
    duration: 139, age: 12, country: 'США', director: 'Дэниэл Квон, Дэниэл Шайнерт',
    cast: ['Мишель Ео', 'Джейми Ли Кёртис', 'Ки Хёй Куан'],
    trailerUrl: 'https://www.youtube.com/embed/wxN1T1uxQ2g', type: 'movie',
  },
  {
    id: 17, title: 'Дикий робот', originalTitle: 'The Wild Robot', year: 2024,
    genres: ['Фантастика', 'Драма', 'Приключения'], rating: 8.4,
    description: 'Робот РОЗУМ попадает на необитаемый остров и учится выживать среди дикой природы, воспитывая гусёнка.',
    shortDesc: 'Самый трогательный анимационный фильм 2024 года.',
    poster: 'https://image.tmdb.org/t/p/w500/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/417X5DRfMHdBCB1TIVWOlEpF1tZ.jpg',
    duration: 101, age: 6, country: 'США', director: 'Крис Сандерс',
    trailerUrl: 'https://www.youtube.com/embed/bo3SIESqsAY', type: 'movie', isFeatured: true,
  },
  {
    id: 18, title: 'Субстанция', originalTitle: 'The Substance', year: 2024,
    genres: ['Ужасы', 'Фантастика'], rating: 7.4,
    description: 'Знаменитость использует экспериментальный препарат для создания молодой версии себя. Цена совершенства высока.',
    shortDesc: 'Боди-хоррор об одержимости красотой и вечной молодостью.',
    poster: 'https://image.tmdb.org/t/p/w500/lqoMzCcZYEFK729d6qzt349fB4o.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg',
    duration: 141, age: 18, country: 'Франция', director: 'Корали Фаржа',
    cast: ['Деми Мур', 'Маргарет Куолли'],
    trailerUrl: 'https://www.youtube.com/embed/lGcAneurA7A', type: 'movie',
  },
  {
    id: 19, title: 'Социальная сеть', originalTitle: 'The Social Network', year: 2010,
    genres: ['Драма', 'Триллер'], rating: 7.8,
    description: 'История создания Facebook. Марк Цукерберг — гений или предатель? Судебные иски бывших партнёров решат это.',
    shortDesc: 'Как студент Гарварда создал крупнейшую соцсеть и потерял друзей.',
    poster: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/lXRdmApT5AXqRJ5bvjUkgxKJbwO.jpg',
    duration: 120, age: 12, country: 'США', director: 'Дэвид Финчер',
    cast: ['Джесси Айзенберг', 'Эндрю Гарфилд', 'Джастин Тимберлейк'],
    trailerUrl: 'https://www.youtube.com/embed/lB95KLmpLR4', type: 'movie',
  },
  {
    id: 20, title: 'Мстители: Финал', originalTitle: 'Avengers: Endgame', year: 2019,
    genres: ['Боевик', 'Фантастика'], rating: 8.4,
    description: 'Уцелевшие Мстители объединяются для последней битвы с Таносом, чтобы вернуть к жизни половину вселенной.',
    shortDesc: 'Финал 22 фильмов MCU. Грандиозная битва за вселенную.',
    poster: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    duration: 181, age: 12, country: 'США', director: 'Братья Руссо',
    cast: ['Роберт Дауни мл.', 'Крис Эванс', 'Марк Руффало'],
    trailerUrl: 'https://www.youtube.com/embed/TcMBFSGVi1c', type: 'movie',
  },

  // ═══════════════════════════════════════════════════════════════
  //  СЕРИАЛЫ (id: 101–125)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 101, title: 'Игра престолов', originalTitle: 'Game of Thrones', year: 2011,
    genres: ['Фэнтези', 'Драма', 'Боевик'], rating: 9.2,
    description: 'Несколько знатных семей борются за контроль над землями Вестероса, пока с севера надвигается древняя угроза.',
    shortDesc: 'Семьи, предательства и драконы в борьбе за Железный трон.',
    poster: 'https://image.tmdb.org/t/p/w500/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/suopoADq0k8YZr4dQXcU6pToj6s.jpg',
    duration: 57, age: 18, country: 'США', director: 'Дэвид Бениофф',
    trailerUrl: 'https://www.youtube.com/embed/bjqEWgDVPe0',
    type: 'series', seasons: 8, status: 'ended',
  },
  {
    id: 102, title: 'Во все тяжкие', originalTitle: 'Breaking Bad', year: 2008,
    genres: ['Криминал', 'Триллер', 'Драма'], rating: 9.5,
    description: 'Учитель химии с раком превращается в производителя метамфетамина. История распада хорошего человека.',
    shortDesc: 'Лучший сериал в истории. Учитель химии становится наркобаронном.',
    poster: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    duration: 49, age: 18, country: 'США', director: 'Винс Гиллиган',
    cast: ['Брайан Крэнстон', 'Аарон Пол'],
    trailerUrl: 'https://www.youtube.com/embed/HhKNyG4XFLQ',
    type: 'series', seasons: 5, status: 'ended',
  },
  {
    id: 103, title: 'Чернобыль', originalTitle: 'Chernobyl', year: 2019,
    genres: ['Триллер', 'Драма', 'Исторический'], rating: 9.4,
    description: 'Реальная история ядерной катастрофы 1986 года и людей, рисковавших жизнью, чтобы остановить её.',
    shortDesc: 'Ядерная катастрофа и люди, которые её предотвратили. Основано на реальных событиях.',
    poster: 'https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/dCLpX47rKTu0OUYMsHe1Yv0N0v4.jpg',
    duration: 60, age: 16, country: 'США/Великобритания',
    cast: ['Джаред Харрис', 'Стеллан Скарсгорд', 'Эмили Уотсон'],
    trailerUrl: 'https://www.youtube.com/embed/s9APLXM9Ei8',
    type: 'series', seasons: 1, status: 'ended',
  },
  {
    id: 104, title: 'Острые козырьки', originalTitle: 'Peaky Blinders', year: 2013,
    genres: ['Криминал', 'Драма'], rating: 8.8,
    description: 'История гангстерской семьи Шелби из Бирмингема после Первой мировой войны.',
    shortDesc: 'Семья Шелби и её путь от улиц Бирмингема до политики Британии.',
    poster: 'https://image.tmdb.org/t/p/w500/vUUqzWa2LnHIVqkaKVn3nyfxRsp.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/wiE9doxiLwq3WCGamCCAaQ8JPOF.jpg',
    duration: 60, age: 18, country: 'Великобритания', director: 'Стивен Найт',
    cast: ['Киллиан Мёрфи', 'Хелен МакКрори', 'Пол Андерсон'],
    trailerUrl: 'https://www.youtube.com/embed/oVzVdvGIC7U',
    type: 'series', seasons: 6, status: 'ended',
  },
  {
    id: 105, title: 'Последние из нас', originalTitle: 'The Last of Us', year: 2023,
    genres: ['Боевик', 'Драма', 'Фантастика'], rating: 8.8,
    description: 'В мире, поражённом грибковой пандемией, контрабандист Джоэл везёт девочку-подростка через Америку.',
    shortDesc: 'Лучшая экранизация видеоигры. Апокалипсис и человечность.',
    poster: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95iFVDBedY.jpg',
    duration: 55, age: 18, country: 'США',
    cast: ['Педро Паскаль', 'Белла Рэмси'],
    trailerUrl: 'https://www.youtube.com/embed/uLtkt8BonwM',
    type: 'series', seasons: 2, status: 'ongoing',
  },
  {
    id: 106, title: 'Разделение', originalTitle: 'Severance', year: 2022,
    genres: ['Фантастика', 'Триллер', 'Драма'], rating: 8.7,
    description: 'Сотрудники Lumon Industries добровольно разделяют рабочую и личную память. Но что скрывается внутри?',
    shortDesc: 'Офис, где рабочая память стёрта. Что происходит с тобой внутри?',
    poster: 'https://image.tmdb.org/t/p/w500/pqzjCxPVc9TkVgGRWeAoMmyqkZV.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/lRbSCZkb0B9N9aJqgmPoEZKGJAg.jpg',
    duration: 55, age: 16, country: 'США',
    trailerUrl: 'https://www.youtube.com/embed/xEQP4VVuyrY',
    type: 'series', seasons: 2, status: 'ongoing',
  },
  {
    id: 107, title: 'Медведь', originalTitle: 'The Bear', year: 2022,
    genres: ['Драма', 'Комедия'], rating: 8.8,
    description: 'Шеф-повар из высокой кухни возвращается в Чикаго, чтобы спасти семейный ресторанчик.',
    shortDesc: 'Самый напряжённый сериал о кухне. Не о еде — о людях.',
    poster: 'https://image.tmdb.org/t/p/w500/mWDJmgPpFjLTGmfgagz0TXn96AY.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/q9z5DQHF2vBBuVTUiJW3W1rBiRi.jpg',
    duration: 30, age: 16, country: 'США',
    cast: ['Джереми Аллен Уайт', 'Эйо Эдебири'],
    trailerUrl: 'https://www.youtube.com/embed/XZQEFqr-vP4',
    type: 'series', seasons: 3, status: 'ongoing',
  },
  {
    id: 108, title: 'Настоящий детектив', originalTitle: 'True Detective', year: 2014,
    genres: ['Криминал', 'Триллер', 'Драма'], rating: 9.0,
    description: 'Двое детективов расследуют серию жестоких убийств в Луизиане на протяжении 17 лет.',
    shortDesc: 'Философский криминал. Первый сезон — шедевр.',
    poster: 'https://image.tmdb.org/t/p/w500/lbccgSEjG0JCOoq5XJ0iyFtEMPv.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/bxOBPfT4f2p2V0UVnKWdBGjBi5m.jpg',
    duration: 55, age: 18, country: 'США',
    cast: ['Мэттью МакКонахи', 'Вуди Харрельсон'],
    trailerUrl: 'https://www.youtube.com/embed/3b4ELFQXqAQ',
    type: 'series', seasons: 4, status: 'ongoing',
  },
  {
    id: 109, title: 'Тьма', originalTitle: 'Dark', year: 2017,
    genres: ['Фантастика', 'Триллер', 'Драма'], rating: 8.8,
    description: 'В немецком городке пропадают дети. Четыре семьи раскрывают заговор, связанный с временными петлями.',
    shortDesc: 'Самая сложная и захватывающая история о путешествиях во времени.',
    poster: 'https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/jJsD4cNnSGUwtAYTB6AXtFMckmN.jpg',
    duration: 60, age: 16, country: 'Германия',
    trailerUrl: 'https://www.youtube.com/embed/rrwycJ08PSA',
    type: 'series', seasons: 3, status: 'ended',
  },
  {
    id: 110, title: 'Бумажный дом', originalTitle: 'La Casa de Papel', year: 2017,
    genres: ['Криминал', 'Триллер', 'Драма'], rating: 8.3,
    description: 'Таинственный Профессор собирает банду и организует ограбление Монетного двора Испании.',
    shortDesc: 'Белла Чао. Ограбление века в прямом эфире.',
    poster: 'https://image.tmdb.org/t/p/w500/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/piuCEYTdJMWaBQnmq16JrxqujqE.jpg',
    duration: 50, age: 16, country: 'Испания',
    trailerUrl: 'https://www.youtube.com/embed/htIPwSiRuqY',
    type: 'series', seasons: 5, status: 'ended',
  },

  // ═══════════════════════════════════════════════════════════════
  //  АНИМЕ (id: 201–225)
  // ═══════════════════════════════════════════════════════════════
  {
    id: 201, title: 'Атака титанов', originalTitle: 'Shingeki no Kyojin', year: 2013,
    genres: ['Боевик', 'Фэнтези', 'Аниме'], rating: 9.0,
    description: 'Человечество живёт внутри огромных стен, защищающих от гигантских существ — титанов.',
    shortDesc: 'Стены рушатся. Люди узнают правду о своём мире.',
    poster: 'https://image.tmdb.org/t/p/w500/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/vSMnbPpxFLHQMZVKIpPx7qxFUzM.jpg',
    duration: 24, age: 16, country: 'Япония',
    trailerUrl: 'https://www.youtube.com/embed/MGRm4IzK1SQ',
    type: 'anime', seasons: 4, status: 'ended', isFeatured: true,
  },
  {
    id: 202, title: 'Клинок, рассекающий демонов', originalTitle: 'Kimetsu no Yaiba', year: 2019,
    genres: ['Боевик', 'Фэнтези', 'Аниме'], rating: 8.7,
    description: 'После гибели семьи Танджиро Камадо отправляется искать лекарство от демонической болезни сестры.',
    shortDesc: 'Самое красивое аниме о демонах и борьбе духа.',
    poster: 'https://image.tmdb.org/t/p/w500/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
    duration: 23, age: 16, country: 'Япония',
    trailerUrl: 'https://www.youtube.com/embed/6vMuWuWlW4I',
    type: 'anime', seasons: 4, status: 'ongoing',
  },
  {
    id: 203, title: 'Стальной алхимик: Братство', originalTitle: 'Fullmetal Alchemist: Brotherhood', year: 2009,
    genres: ['Боевик', 'Фэнтези', 'Аниме'], rating: 9.1,
    description: 'Братья Элрик ищут Философский камень, чтобы вернуть тела после неудачного алхимического ритуала.',
    shortDesc: 'Лучшее аниме по опросам. Братья, алхимия и цена жизни.',
    poster: 'https://image.tmdb.org/t/p/w500/5ZFUEOULaVml7ozfy4uoMOeBoqu.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/5ZFUEOULaVml7ozfy4uoMOeBoqu.jpg',
    duration: 24, age: 12, country: 'Япония',
    trailerUrl: 'https://www.youtube.com/embed/--IcmZkvL0Q',
    type: 'anime', seasons: 1, status: 'ended',
  },
  {
    id: 204, title: 'Унесённые призраками', originalTitle: 'Sen to Chihiro no Kamikakushi', year: 2001,
    genres: ['Фэнтези', 'Приключения', 'Аниме'], rating: 9.3,
    description: 'Девочка попадает в мир духов и вынуждена работать в купальне, чтобы спасти превращённых в свиней родителей.',
    shortDesc: 'Шедевр Миядзаки. Оскар за лучший анимационный фильм.',
    poster: 'https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/bSXfU4dwZyBA1vMmXvejdRXBvuF.jpg',
    duration: 125, age: 6, country: 'Япония', director: 'Хаяо Миядзаки',
    trailerUrl: 'https://www.youtube.com/embed/ByXuk9QqQkk',
    type: 'anime', isFeatured: true,
  },
  {
    id: 205, title: 'Врата Штейна', originalTitle: 'Steins;Gate', year: 2011,
    genres: ['Фантастика', 'Триллер', 'Аниме'], rating: 9.1,
    description: 'Эксцентричный учёный случайно создаёт машину времени из микроволновки. Путешествия по прошлому меняют всё.',
    shortDesc: 'Лучшее аниме о путешествиях во времени. Эль Пси Конгру.',
    poster: 'https://image.tmdb.org/t/p/w500/8uODfFjpHFLdUB1OuiX0BuPcfWm.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/mQxKJJGBSQFwFNOlSi0NN3hGTdH.jpg',
    duration: 23, age: 16, country: 'Япония',
    trailerUrl: 'https://www.youtube.com/embed/27OZc-ku6is',
    type: 'anime', seasons: 1, status: 'ended',
  },
  {
    id: 206, title: 'Виолет Эвергарден', originalTitle: 'Violet Evergarden', year: 2018,
    genres: ['Драма', 'Фэнтези', 'Аниме'], rating: 8.9,
    description: 'После войны бывший солдат Виолет становится автодольщицей писем и учится понимать человеческие чувства.',
    shortDesc: 'Самое красивое аниме. История о любви, потере и силе слов.',
    poster: 'https://image.tmdb.org/t/p/w500/9BJanm7jHkQjKhPFluTWsLJR9Eg.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/1qpUk27LVI9UoTS7S0EderUy6Zo.jpg',
    duration: 24, age: 12, country: 'Япония',
    trailerUrl: 'https://www.youtube.com/embed/0CJeDetA45Q',
    type: 'anime', seasons: 1, status: 'ended',
  },
  {
    id: 207, title: 'Магическая битва', originalTitle: 'Jujutsu Kaisen', year: 2020,
    genres: ['Боевик', 'Фэнтези', 'Аниме'], rating: 8.6,
    description: 'Старшеклассник проглатывает проклятый палец и становится носителем сильнейшего демона.',
    shortDesc: 'Лучший боевик последних лет. Проклятия, техники и эпические бои.',
    poster: 'https://image.tmdb.org/t/p/w500/oMBGbQFxAEk0QXrMhxQT8Fz9fPS.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/gHBfPDFDIZRaXxKl2oDRdiJfMMf.jpg',
    duration: 23, age: 16, country: 'Япония',
    trailerUrl: 'https://www.youtube.com/embed/pkKu9hLT-t8',
    type: 'anime', seasons: 2, status: 'ongoing',
  },
  {
    id: 208, title: 'Ван Пис', originalTitle: 'One Piece', year: 1999,
    genres: ['Боевик', 'Приключения', 'Аниме', 'Комедия'], rating: 8.9,
    description: 'Мальчик Луффи мечтает стать Королём пиратов. Он набирает команду и плывёт к легендарному сокровищу.',
    shortDesc: 'Самое длинное аниме с лучшим миром. 1000+ серий без скуки.',
    poster: 'https://image.tmdb.org/t/p/w500/fcXdJlbSqiIku76fOjpjaTSo7GZ.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fcXdJlbSqiIku76fOjpjaTSo7GZ.jpg',
    duration: 24, age: 12, country: 'Япония',
    trailerUrl: 'https://www.youtube.com/embed/MCvW2OdaBAA',
    type: 'anime', seasons: 21, status: 'ongoing',
  },
  {
    id: 209, title: 'Ваш апрель в лжи', originalTitle: 'Shigatsu wa Kimi no Uso', year: 2014,
    genres: ['Драма', 'Музыка', 'Аниме'], rating: 8.7,
    description: 'Бывший вундеркинд-пианист встречает яркую скрипачку, которая возвращает ему радость от музыки.',
    shortDesc: 'Самое душераздирающее аниме о музыке, жизни и прощании.',
    poster: 'https://image.tmdb.org/t/p/w500/qGN61ajJNKMsTgCLlvhpz4dIwCP.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/kaFDvApXbhTDMXxYivW0gU1qw3S.jpg',
    duration: 22, age: 12, country: 'Япония',
    trailerUrl: 'https://www.youtube.com/embed/NpGW8DQMH4E',
    type: 'anime', seasons: 1, status: 'ended',
  },
  {
    id: 210, title: 'Соло ролевой игрок', originalTitle: 'Solo Leveling', year: 2024,
    genres: ['Боевик', 'Фэнтези', 'Аниме'], rating: 8.5,
    description: 'Слабейший охотник получает уникальную способность прокачиваться без ограничений и становится сильнейшим.',
    shortDesc: 'Система прокачки, порталы и путь от слабейшего к непобедимому.',
    poster: 'https://image.tmdb.org/t/p/w500/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8nQqGHN7dBmUlzO3YYpS6c7yNLM.jpg',
    duration: 23, age: 16, country: 'Япония/Южная Корея',
    trailerUrl: 'https://www.youtube.com/embed/DkJlbsY5xfA',
    type: 'anime', seasons: 2, status: 'ongoing', isFeatured: true,
  },
]

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI)
    console.log('MongoDB подключена')

    await Movie.deleteMany({})
    console.log('Старые данные очищены')

    await Movie.insertMany(movies)
    console.log(`✅ Добавлено ${movies.length} записей:`)
    console.log(`   Фильмы:  ${movies.filter(m => m.type === 'movie').length}`)
    console.log(`   Сериалы: ${movies.filter(m => m.type === 'series').length}`)
    console.log(`   Аниме:   ${movies.filter(m => m.type === 'anime').length}`)

    await mongoose.disconnect()
    console.log('\n🎬 База данных заполнена! Запустите: npm run seed:admin')
    process.exit(0)
  } catch (error) {
    console.error('Ошибка:', error.message)
    process.exit(1)
  }
}

seedDB()
